spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia%2FShanghai"
      username: "root"
      password: "123456"
    quartz:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/demo_quartz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia%2FShanghai"
      username: "root"
      password: "123456"
  redis:
    client-type: lettuce
    host: localhost
    port: 6379
    database: 0
  cache:
    type: redis
  session:
    store-type: redis
    redis:
      flush-mode: immediate
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

storage:
  aliyun:
    access-key-id: ""
    access-key-secret: ""
    endpoint: ""
    bucket: ""

order-no-generator:
  global-prefix: ""