spring:
  data:
    redis:
      client-type: lettuce
  cache:
    type: redis
  session:
    redis:
      flush-mode: immediate
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  servlet:
    multipart:
      max-file-size: 125MB
      max-request-size: 256MB